### PR TITLE
Update request_information.go

### PR DESCRIPTION
**Pull request by gu-colin-morris**
Typo correction for content type:
 - "application/octet-stream" replacing "application/octet-steam"

### CODE REVIEW

**Review by SilasKenneth — APPROVED** [review]

**Review by andrueastman — COMMENTED** [review]
Thanks for fixing this @gu-colin-morris 

Any chance you could add a changelog entry for the same with a patch version number update?

https://github.com/microsoft/kiota-abstractions-go/blob/main/CHANGELOG.md

**Comment by gu-colin-morris** [comment]
Sure can. I've found another of the "octet-steam" entries, do you want that in the same patch commit?

**Comment by gu-colin-morris** [comment]
Sure can. I've found another "octet-steam" - do you want that in the same patch? (assuming 1.8.1)

**Comment by andrueastman** [comment]
Sure thing. We can have them all together.

> Sure can. I've found another "octet-steam" - do you want that in the same patch? (assuming 1.8.1)

**Review by andrueastman — APPROVED** [review]

**Pull request merged**
